project:
  type: website
  output-dir: web_output

website:
  title: "Shangxuan Zhong"

  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd



